version: 2.1
orbs:
  tfupdate: masutaka/tfupdate@volatile

jobs:
  tfupdate:
    executor: tfupdate/default
    steps:
      - checkout
      - tfupdate/setup:
          git_user_name: 'tfupdate-circleci'
          git_user_email: 'minamijoyo+tfupdate-circleci@gmail.com'
      - tfupdate/terraform
      - tfupdate/provider:
          provider_name: 'aws'

workflows:
  version: 2
  scheduled:
    jobs:
      - tfupdate
    triggers:
      - schedule:
          cron: "0 0 * * *"  # minute hour day month week (UTC)
          filters:
            branches:
              only:
                - master
  tfupdate_test:
    jobs:
      - tfupdate:
          filters:
            branches:
              only:
                - /tfupdate-.*/
